name: sa7ety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_firebase_chat_core: ^1.6.8
  lottie: ^3.2.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Medium.ttf
          weight: 500
