name: sa7ety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_firebase_chat_core: ^1.6.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  localization: ^2.1.1
  lottie: ^3.2.0
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.0+3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Medium.ttf
          weight: 500
