// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GScEL8-5iSaLO2t53ev7cpPb1CMxB6k',
    appId: '1:914285582832:android:735d1701d0a7219993e535',
    messagingSenderId: '914285582832',
    projectId: 'sa7ety-1',
    storageBucket: 'sa7ety-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ggclkuqU4nyUbP0DNSzhma28X7XytOw',
    appId: '1:914285582832:ios:4d6b2edfae13183293e535',
    messagingSenderId: '914285582832',
    projectId: 'sa7ety-1',
    storageBucket: 'sa7ety-1.firebasestorage.app',
    iosBundleId: 'com.example.sa7ety',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeRWpNT1010oONzDWsL2C7mZ6DvIB9lmM',
    appId: '1:914285582832:web:d428d74f522c171d93e535',
    messagingSenderId: '914285582832',
    projectId: 'sa7ety-1',
    authDomain: 'sa7ety-1.firebaseapp.com',
    storageBucket: 'sa7ety-1.firebasestorage.app',
    measurementId: 'G-H01739JXCB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ggclkuqU4nyUbP0DNSzhma28X7XytOw',
    appId: '1:914285582832:ios:4d6b2edfae13183293e535',
    messagingSenderId: '914285582832',
    projectId: 'sa7ety-1',
    storageBucket: 'sa7ety-1.firebasestorage.app',
    iosBundleId: 'com.example.sa7ety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeRWpNT1010oONzDWsL2C7mZ6DvIB9lmM',
    appId: '1:914285582832:web:b3f3d0cfe1bc1ad093e535',
    messagingSenderId: '914285582832',
    projectId: 'sa7ety-1',
    authDomain: 'sa7ety-1.firebaseapp.com',
    storageBucket: 'sa7ety-1.firebasestorage.app',
    measurementId: 'G-B8ZRGPECG8',
  );

}